### ISSUE TITLE
How to query another column like "birthYear" bigint

### ISSUE THREAD

**Issue by pomeloguy** [ReverseControl/MuchPIR#9]
i want to try modify pri_select--1.0.sql，but not work .

"This demo targets string types on postgres, but can easily be adapted to query any type: int4, int8, float, bytea, etc."

how to work it

**Comment by ReverseControl** [comment]
By easily, I meant, if you already know C and C++ fundamentals on types. I won't be publishing those any time soon but you are welcome to implement them. I will merge those improvements if they are submitted to the repo. 

The purpose of this repo is simply to prove, by exhibiting a real implementation, that PIR is doable on a real database; and hopefully, the claim that a practical implementation exists based on that work is at least taken somewhat seriously by folks who care about this topic.  

The MuchPIR whitepaper is not published either. At least for now. Any commercial interest is welcome to email me, the contact info is on the Readme file.
